In [1]:
import numpy as np
from sympy import * #var, Lambda, exp, log, sin, cos, tan, sqrt, ln

In [2]:
# Dados iniciais [n,    Tipo,   V, teta,     P,     Q]
Matriz_Barras = [[1,    'PQ', '?',  '?', -0.15,  0.05, complex(0, 0.05)],
                 [2, 'VTeta',   1,    0,   '?',   '?',  '?'],
                 [3,    'PV',   1,  '?',   0.2,   '?',  '?']]

# Dados iniciais      [k, m, Z_km]
Matriz_Impedancias = [[1, 2, complex(0.03, 0.3), complex(0, 0.02)],
                      [2, 3, complex(0.05, 0.8), complex(0, 0.01)]]

y11 =  (Matriz_Impedancias[0][2])**(-1) + (Matriz_Impedancias[0][3]) + (Matriz_Barras[0][6])
y12 = -(Matriz_Impedancias[0][2])**(-1)
y13 =  0
y21 =  y12
y22 =  (Matriz_Impedancias[0][2])**(-1) + (Matriz_Impedancias[1][2])**(-1) + (Matriz_Impedancias[0][3]) + (Matriz_Impedancias[1][3])
y23 = -(Matriz_Impedancias[1][2])**(-1)
y31 =  y13
y32 =  y23
y33 =  (Matriz_Impedancias[1][2])**(-1) + (Matriz_Impedancias[1][3])

Y = np.array([[y11, y12,y13], [y21, y22, y23], [y31, y32, y33]]) # Matriz Adimitancia

G = Y.real
B = Y.imag

print('\nY = ', Y)
print('\nG = ', G)
print('\nB = ', B)


Y =  [[ 0.330033  -3.23033003j -0.330033  +3.30033003j  0.        +0.j        ]
 [-0.330033  +3.30033003j  0.40785401-4.51546622j -0.07782101+1.24513619j]
 [ 0.        +0.j         -0.07782101+1.24513619j  0.07782101-1.23513619j]]

G =  [[ 0.330033   -0.330033    0.        ]
 [-0.330033    0.40785401 -0.07782101]
 [ 0.         -0.07782101  0.07782101]]

B =  [[-3.23033003  3.30033003  0.        ]
 [ 3.30033003 -4.51546622  1.24513619]
 [ 0.          1.24513619 -1.23513619]]


In [3]:
teta1,teta3,V1 = var('teta1 teta3 V1') # Variaveis simbolicas
teta2, V2, V3 = Matriz_Barras[1][3], Matriz_Barras[1][2], Matriz_Barras[2][2] # Variaveis numericas

# Potências esperadas nas barras 
P_esp_1 = Matriz_Barras[0][4]
P_esp_3 = Matriz_Barras[2][4]
Q_esp_1 = Matriz_Barras[0][5]

# Vetor de potencias
DeltaP1 = Lambda((teta1,teta3,V1), P_esp_1 - V1*( V1*(G[0,0]*cos(teta1-teta1) + B[0,0]*sin(teta1-teta1)) +                                                  
                                                  V2*(G[0,1]*cos(teta1-teta2) + B[0,1]*sin(teta1-teta2)) ))

DeltaP3 = Lambda((teta1,teta3,V1), P_esp_3 - V3*( V3*(G[2,2]*cos(teta3-teta3) + B[2,2]*sin(teta3-teta3)) + 
                                                  V2*(G[2,1]*cos(teta3-teta2) + B[2,1]*sin(teta3-teta2)) ))

DeltaQ1 = Lambda((teta1,teta3,V1), Q_esp_1 - V1*( V1*(G[0,0]*sin(teta1-teta1) - B[0,0]*cos(teta1-teta1)) +                                                  
                                                  V2*(G[0,1]*sin(teta1-teta2) - B[0,1]*cos(teta1-teta2)) ))

Delta_P_Q = [[DeltaP1],[DeltaP3],[DeltaQ1]]

for i in range(len(Delta_P_Q)):
    print('\nDelta_P_Q[',i+1,'] = ', Delta_P_Q[i][0](teta2,teta3,V3))


Delta_P_Q[ 1 ] =  -0.150000000000000

Delta_P_Q[ 2 ] =  -1.24513618677043*sin(teta3) + 0.0778210116731517*cos(teta3) + 0.122178988326848

Delta_P_Q[ 3 ] =  0.120000000000000


In [4]:
# Matriz Jacobiana
j11 = Lambda((teta1,teta3,V1), diff(DeltaP1(teta1,teta3,V1),teta1))
j12 = Lambda((teta1,teta3,V1), diff(DeltaP1(teta1,teta3,V1),teta3))
j13 = Lambda((teta1,teta3,V1), diff(DeltaP1(teta1,teta3,V1),V1))

j21 = Lambda((teta1,teta3,V1), diff(DeltaP3(teta1,teta3,V1),teta1))
j22 = Lambda((teta1,teta3,V1), diff(DeltaP3(teta1,teta3,V1),teta3))
j23 = Lambda((teta1,teta3,V1), diff(DeltaP3(teta1,teta3,V1),V1))

j31 = Lambda((teta1,teta3,V1), diff(DeltaQ1(teta1,teta3,V1),teta1))
j32 = Lambda((teta1,teta3,V1), diff(DeltaQ1(teta1,teta3,V1),teta3))
j33 = Lambda((teta1,teta3,V1), diff(DeltaQ1(teta1,teta3,V1),V1))

J = [[j11, j12, j13],
     [j21, j22, j23],
     [j31, j32, j33]]

for i in range(len(J)):
    for j in range(len(J)):
        print('J[',i+1,'][',j+1,'] = ', J[i][j](teta1,teta3,V1))
    print('\n')

J[ 1 ][ 1 ] =  -V1*(0.33003300330033*sin(teta1) + 3.3003300330033*cos(teta1))
J[ 1 ][ 2 ] =  0
J[ 1 ][ 3 ] =  -0.66006600660066*V1 - 3.3003300330033*sin(teta1) + 0.33003300330033*cos(teta1)


J[ 2 ][ 1 ] =  0
J[ 2 ][ 2 ] =  -0.0778210116731517*sin(teta3) - 1.24513618677043*cos(teta3)
J[ 2 ][ 3 ] =  0


J[ 3 ][ 1 ] =  -V1*(3.3003300330033*sin(teta1) - 0.33003300330033*cos(teta1))
J[ 3 ][ 2 ] =  0
J[ 3 ][ 3 ] =  -6.4606600660066*V1 + 0.33003300330033*sin(teta1) + 3.3003300330033*cos(teta1)




In [5]:
# Vetor inicial

teta2_inicial, teta3_inicial, V3_inicial = 0, 0, 1 # Chute inicial
teta_V = [[teta2_inicial], 
          [teta3_inicial],
          [V3_inicial]]

Delta_teta_V = [[0], 
                [0], 
                [0]]

# Erro
Ep = 0.001
Eq = 0.001

# Numeros de iterações
Iteracao = -1
Max_Iteracao = 10

J1 = [[0,0,0],[0,0,0],[0,0,0]]
for i in range(len(J)):
    for j in range(len(J)):
        J1[i][j] = np.float(J[i][j](teta_V[0][0],teta_V[1][0],teta_V[2][0]))
J_inv = np.linalg.inv(J1)


<ipython-input-5-d8d6b1270d09>:23: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  J1[i][j] = np.float(J[i][j](teta_V[0][0],teta_V[1][0],teta_V[2][0]))


In [6]:
def Imprime(Iteracao, teta_V, Delta_P_Q, J, J_inv, Delta_teta_V):
    # Estado inicial
    print('Iteração: ', Iteracao)
    print('\n')
    
    for i in range(len(teta_V)):
        print('teta_V[',i+1,'] = ', teta_V[i][0])
    print('\n')

    for i in range(len(Delta_P_Q)):
        print('Delta_P_Q[',i+1,'] = ', Delta_P_Q[i][0](teta_V[0][0],teta_V[1][0],teta_V[2][0]))
    print('\n')

    for i in range(len(J)):
        for j in range(len(J)):
            print('J[',i+1,'][',j+1,'] = ', J[i][j](teta_V[0][0],teta_V[1][0],teta_V[2][0]))
    print('\n')

    for i in range(len(J_inv)):
        for j in range(len(J_inv)):
            print('J_inv[',i+1,'][',j+1,'] = ', J_inv[i][j])
        
    print('\n')

    for i in range(len(Delta_teta_V)):
        print('Delta_teta_V[',i+1,'] = ', Delta_teta_V[i][0])
    print('\n')

In [7]:
# Algoritmo de Newton-Raphson

while (Iteracao < Max_Iteracao):
    Iteracao += 1
    for i in range(len(Delta_teta_V)):
        Delta_teta_V[i][0] = 0

    for i in range(len(Delta_teta_V)):
        for j in range(len(Delta_P_Q)):
            Delta_teta_V[i][0] += -J_inv[i][j]*Delta_P_Q[j][0](teta_V[0][0],teta_V[1][0],teta_V[2][0])
    
    Imprime(Iteracao, teta_V, Delta_P_Q, J, -J_inv, Delta_teta_V)
    
    for i in range(len(Delta_teta_V)):
        teta_V[i][0] += Delta_teta_V[i][0]
        
    if (abs(Delta_teta_V[0][0]) < Ep and abs(Delta_teta_V[1][0]) < Ep and abs(Delta_teta_V[2][0]) < Eq):
        break
    
    for i in range(len(J)):
        for j in range(len(J)):
            J1[i][j] = np.float(J[i][j](teta_V[0][0],teta_V[1][0],teta_V[2][0]))
    J_inv = np.linalg.inv(J1)

Iteração:  0


teta_V[ 1 ] =  0
teta_V[ 2 ] =  0
teta_V[ 3 ] =  1


Delta_P_Q[ 1 ] =  -0.150000000000000
Delta_P_Q[ 2 ] =  0.200000000000000
Delta_P_Q[ 3 ] =  0.120000000000000


J[ 1 ][ 1 ] =  -3.30033003300330
J[ 1 ][ 2 ] =  0
J[ 1 ][ 3 ] =  -0.330033003300330
J[ 2 ][ 1 ] =  0
J[ 2 ][ 2 ] =  -1.24513618677043
J[ 2 ][ 3 ] =  0
J[ 3 ][ 1 ] =  0.330033003300330
J[ 3 ][ 2 ] =  0
J[ 3 ][ 3 ] =  -3.16033003300330


J_inv[ 1 ][ 1 ] =  0.2998684759916493
J_inv[ 1 ][ 2 ] =  0.0
J_inv[ 1 ][ 3 ] =  -0.031315240083507306
J_inv[ 2 ][ 1 ] =  0.0
J_inv[ 2 ][ 2 ] =  0.8031250000000001
J_inv[ 2 ][ 3 ] =  0.0
J_inv[ 3 ][ 1 ] =  0.031315240083507306
J_inv[ 3 ][ 2 ] =  0.0
J_inv[ 3 ][ 3 ] =  0.313152400835073


Delta_teta_V[ 1 ] =  -0.0487381002087683
Delta_teta_V[ 2 ] =  0.160625000000000
Delta_teta_V[ 3 ] =  0.0328810020876826


Iteração:  1


teta_V[ 1 ] =  -0.0487381002087683
teta_V[ 2 ] =  0.160625000000000
teta_V[ 3 ] =  1.03288100208768


Delta_P_Q[ 1 ] =  0.00446159374815036
Delta_P_Q[ 2 ] =  -0

<ipython-input-7-9c0fa8807dcd>:22: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  J1[i][j] = np.float(J[i][j](teta_V[0][0],teta_V[1][0],teta_V[2][0]))


In [8]:
P1 = Lambda((teta2,teta3,V3), V1*(V2*(G[0,1]*cos(teta1 - teta2) + B[0,1]*sin(teta1-teta2)) + 
                                  V1*(G[0,0]*cos(teta1 - teta1) + B[0,0]*sin(teta1-teta1))))

Q1 = Lambda((teta2,teta3,V3), V1*(V2*(G[0,1]*sin(teta1 - teta2) - B[0,1]*cos(teta1-teta2)) +
                                  V1*(G[0,0]*sin(teta1 - teta1) - B[0,0]*cos(teta1-teta1))))

Q2 = Lambda((teta2,teta3,V3), V2*(V1*(G[1,0]*sin(teta2 - teta1) - B[1,0]*cos(teta2-teta1)) +
                                  V2*(G[1,1]*sin(teta2 - teta2) - B[1,1]*cos(teta2-teta2)) + 
                                  V3*(G[1,2]*sin(teta2 - teta3) - B[1,2]*cos(teta2-teta3)) ))

Resp = [[P1],[Q1],[Q2]]
print(teta_V)
for i in range(len(Resp)):
    print('\nDelta_P_Q[',i+1,'] = ', np.float(Resp[i][0](teta_V[0][0],teta_V[1][0],teta_V[2][0])))

BadSignatureError: Lambda signature should be only tuples and symbols, not 0