In [1]:
import numpy as np
from sympy import * #var, Lambda, exp, log, sin, cos, tan, sqrt, ln
from Materia_da_P4 import Fluxo_de_carga

In [2]:
Matriz_Impedancias = {

    "1" : {"2": 0.012 +0.3j},

    "2" : {"1": 0.012 +0.3j, 
           "3": 0.011 +0.8j},

    "3" : {"2": 0.011 +0.8j} }
# Dados iniciais [n,    Tipo,   V, T,     P,     Q]
Matriz_Barras = {
        "1" : {"VT": [   1,    0, "EP1", "Q1"]},
        "2" : {"PV": [   1, "T2",   0.2, "Q2"]},
        "3" : {"PQ": ["V3", "T3", -0.15, 0.05]} }



In [3]:
V1, V2, V3 =  1, 1, var('V3')
T1, T2, T3 =  0, var('T2'), var('T3')
V = [V1, V2, V3]
T = [T1, T2, T3]
P = []
'''for k in (Matriz_Impedancias):
    for m in (Matriz_Impedancias[k]):
        Px = V[k]*(V[m]*(G[k,m]*cos(T[k]-T[m]) + B[k,m]*cos(T[k]-T[m])))
    P[k] += Px'''

TypeError: list indices must be integers or slices, not str

In [4]:
Q1 = Fluxo_de_carga(Ep = 1, Eq = 1)
Y, G, B = Q1.matriz_admitancia(Matriz_Impedancias)
Q1.define_variaveis(Matriz_Barras)
Q1.matriz_equacoes(Matriz_Impedancias)


Y = 
[[ 0.13312-3.32801j -0.13312+3.32801j  0.     +0.j     ]
 [-0.13312+3.32801j  0.1503 -4.57777j -0.01718+1.24976j]
 [ 0.     +0.j      -0.01718+1.24976j  0.01718-1.24976j]]

G = 
[[ 0.13312 -0.13312  0.     ]
 [-0.13312  0.1503  -0.01718]
 [ 0.      -0.01718  0.01718]]

B = 
[[-3.32801  3.32801  0.     ]
 [ 3.32801 -4.57777  1.24976]
 [ 0.       1.24976 -1.24976]]

V1, V2, V3 =  [1, 1, V3]

T1, T2, T3 =  [0, T2, T3]

P_Q_esp =  [0.2, -0.15, 0.05]


TypeError: 'Lambda' object is not iterable